Add JSON support for formatting output data
p-ranav/fccf pull request #7
Opened 2022-05-06 11:32 UTC by btaczala

This commit adds JSON support for formatting results. I'd like to hook fccf into other tools (neovim) and it's much easier to parse JSON that plain text. 

This adds a 3rdParty dependency (awesome [nlohmann json](https://github.com/nlohmann/json) library) - hope you won't mind.

2022-05-06 23:35 UTC, p-ranav commented
Hello @btaczala. Thanks for the PR. I like the idea and I want to merge it. I've made some minor suggestions (style related) and asked a few questions. Once these are resolved, we can merge. Thanks.

2022-05-13 04:46 UTC, p-ranav requested changes

2022-05-25 21:10 UTC, btaczala commented on source/searcher.cpp
> +void printPlainText(std::string_view filename,
Fixed in fdf3c7091bd8f26af86270107a27029b7a4e3561

2022-05-25 21:11 UTC, btaczala commented on source/main.cpp
> +  nlohmann::json jsonArray = nlohmann::json::array();
Fixed in 17778c2613ffd5e42bb01472f0c9bacdaf9644a9

2022-05-25 21:11 UTC, btaczala commented on test/CMakeLists.txt
> +target_link_libraries(fccf_test PRIVATE fccf_lib libclang)
Fixed in 17778c2613ffd5e42bb01472f0c9bacdaf9644a9

2022-05-25 21:11 UTC, btaczala commented on test/CMakeLists.txt
> +find_package(Clang REQUIRED CONFIG)
Fixed in 17778c2613ffd5e42bb01472f0c9bacdaf9644a9

2022-05-25 21:11 UTC, btaczala commented on source/main.cpp
> +#include "json.hpp"
Fixed in fdf3c7091bd8f26af86270107a27029b7a4e3561

2022-05-27 12:26 UTC, p-ranav approved these changes

2022-05-27 12:26 UTC, merged